<script setup lang="ts">
import { reactive, ref, watch } from 'vue'
import { aiCandidateResolutionLabelMap, aiIssueTypeLabelMap, type AiCandidateEntry, type AiReviewStage, type ModifiedCandidateResult } from '../models/aiReview'

const props = defineProps<{ entry: AiCandidateEntry; stage: AiReviewStage; reviewerName?: string; acting: boolean }>()
const emit = defineEmits<{ accept: [id:string]; reject: [id:string]; modify: [id:string,result:ModifiedCandidateResult] }>()
const editing = ref(false)
const draft = reactive<ModifiedCandidateResult>({ originalText:'',issueType:'wording',suggestion:'',reason:'',pdfPage:1,printedPage:'' })
function resetDraft(){const source=props.entry.resolution.modifiedResult??props.entry.candidate;draft.originalText=source.originalText;draft.issueType=source.issueType;draft.suggestion=source.suggestion;draft.reason=source.reason??'';draft.pdfPage=source.pdfPage;draft.printedPage='printedPage' in source?(source.printedPage??''):''}
watch(() => props.entry, () => { editing.value=false;resetDraft() }, { immediate:true,deep:true })
function submit(){emit('modify',props.entry.candidate.id,{originalText:draft.originalText,issueType:draft.issueType,suggestion:draft.suggestion,reason:draft.reason||undefined,pdfPage:Number(draft.pdfPage)||1,printedPage:draft.printedPage||undefined});editing.value=false}
const severityLabels={critical:'严重',major:'重要',minor:'一般',clarification:'澄清'} as const
const judgementLabels={confirmed_error:'确认错误',likely_error:'可能错误',ambiguous:'存在歧义',correct_but_misleading:'正确但可能误导',correct_but_needs_qualification:'正确但需限定'} as const
const confidenceLabels={high:'高',medium:'中',low:'低'} as const
const verificationLabels={not_required:'无需核验',unverified:'未核验',verified:'已核验',insufficient_evidence:'证据不足',manual_check_required:'需人工核验'} as const
</script>
<template>
  <section class="candidate-editor">
    <div class="candidate-heading"><div><span>✦ AI FIRST PASS</span><h2>AI 初校详情</h2></div><b :class="`resolution-${entry.resolution.status}`">{{ aiCandidateResolutionLabelMap[entry.resolution.status] }}</b></div>
    <div class="candidate-scroll">
      <section class="version-card original"><h3>AI 原始版本</h3><dl><div><dt>原文</dt><dd>{{ entry.candidate.originalText }}</dd></div><div><dt>问题类型</dt><dd>{{ aiIssueTypeLabelMap[entry.candidate.issueType] }}</dd></div><div><dt>AI 修改建议</dt><dd>{{ entry.candidate.suggestion }}</dd></div><div><dt>AI 判断理由</dt><dd>{{ entry.candidate.reason }}</dd></div></dl><div class="metadata"><span>PDF {{ entry.candidate.pdfPage }} 页</span><span>严重程度：{{ severityLabels[entry.candidate.severity] }}</span><span>判断：{{ judgementLabels[entry.candidate.judgement] }}</span><span>置信度：{{ confidenceLabels[entry.candidate.confidence] }}</span><span>核验状态：{{ verificationLabels[entry.candidate.verificationStatus] }}</span></div></section>
      <section v-if="entry.candidate.evidence.length" class="evidence"><h3>核验依据</h3><article v-for="(item,index) in entry.candidate.evidence" :key="`${item.title}:${index}`"><strong>{{ item.title }}</strong><span>{{ item.sourceType }} · {{ item.supports }}</span><span v-if="item.effectiveStatus">状态：{{ item.effectiveStatus }}</span><a v-if="item.citationOrUrl" :href="item.citationOrUrl" target="_blank" rel="noreferrer">查看来源</a><em v-if="item.limitations">限制：{{ item.limitations }}</em></article></section>
      <section v-if="entry.resolution.status==='modified'&&entry.resolution.modifiedResult" class="version-card modified"><h3>人工修改后版本</h3><dl><div><dt>原文</dt><dd>{{ entry.resolution.modifiedResult.originalText }}</dd></div><div><dt>问题类型</dt><dd>{{ aiIssueTypeLabelMap[entry.resolution.modifiedResult.issueType] }}</dd></div><div><dt>修改建议</dt><dd>{{ entry.resolution.modifiedResult.suggestion }}</dd></div><div v-if="entry.resolution.modifiedResult.reason"><dt>修改理由</dt><dd>{{ entry.resolution.modifiedResult.reason }}</dd></div></dl></section>
      <div v-if="entry.resolution.resolvedBy" class="resolution-meta">处理人：{{ entry.resolution.resolvedBy }} · {{ entry.resolution.resolvedAt ? new Date(entry.resolution.resolvedAt).toLocaleString('zh-CN') : '' }}</div>
      <form v-if="editing" class="modify-form" @submit.prevent="submit"><h3>修改后采纳</h3><label>原文<textarea v-model="draft.originalText" required rows="2" /></label><label>问题类型<select v-model="draft.issueType"><option v-for="(label,value) in aiIssueTypeLabelMap" :key="value" :value="value">{{ label }}</option></select></label><label>建议<textarea v-model="draft.suggestion" required rows="2" /></label><label>理由<textarea v-model="draft.reason" rows="2" /></label><div class="form-row"><label>PDF 页码<input v-model.number="draft.pdfPage" min="1" type="number" /></label><label>书中页码<input v-model="draft.printedPage" /></label></div><div class="form-actions"><button type="button" @click="editing=false">取消</button><button class="primary" type="submit" :disabled="acting">提交修改</button></div></form>
    </div>
    <div v-if="stage==='human_review_in_progress'&&!editing" class="candidate-actions"><button type="button" :disabled="acting||!reviewerName" @click="emit('accept',entry.candidate.id)">接受</button><button class="modify" type="button" :disabled="acting||!reviewerName" @click="resetDraft();editing=true">修改后采纳</button><button class="reject" type="button" :disabled="acting||!reviewerName" @click="emit('reject',entry.candidate.id)">驳回</button></div>
    <div v-else-if="stage==='completed'" class="readonly-note">本章已完成，AI Candidate resolution 为只读。</div>
  </section>
</template>
<style scoped>
.candidate-editor{display:flex;flex:1;flex-direction:column;min-height:0}.candidate-heading{display:flex;align-items:center;justify-content:space-between;padding:14px 16px 10px}.candidate-heading span{color:#9c824f;font-size:8px;font-weight:700;letter-spacing:.12em}.candidate-heading h2{margin:3px 0 0;color:#263149;font-size:15px}.candidate-heading b{padding:4px 7px;font-size:9px;border-radius:5px}.resolution-pending{color:#9a7131;background:#fbf2dd}.resolution-accepted{color:#4d7397;background:#e8f1fa}.resolution-modified{color:#4e806e;background:#e5f3ed}.resolution-rejected{color:#7f7580;background:#efedf0}.candidate-scroll{flex:1;min-height:0;padding:0 15px 12px;overflow-y:auto}.version-card,.evidence,.modify-form{margin-bottom:10px;padding:10px;color:#5f6e83;background:#fafbfc;border:1px solid #e4e8ee;border-radius:7px}.version-card.original{border-left:3px solid #c8a977}.version-card.modified{border-left:3px solid #6387ad;background:#f4f8fc}.candidate-editor h3{margin:0 0 8px;color:#40506a;font-size:10px}.version-card dl{margin:0}.version-card dl div{margin-top:7px}.version-card dt{color:#909aa9;font-size:8px}.version-card dd{margin:2px 0 0;color:#3c485d;font-size:10px;line-height:1.5;white-space:pre-wrap}.metadata{display:flex;flex-wrap:wrap;gap:5px;margin-top:9px}.metadata span{padding:3px 5px;font-size:8px;background:#edf1f5;border-radius:4px}.evidence article{display:flex;flex-direction:column;gap:3px;padding:7px 0;border-top:1px solid #e7eaf0}.evidence article:first-of-type{border-top:0}.evidence strong{color:#43536c;font-size:9px}.evidence span,.evidence a,.evidence em{font-size:8px;line-height:1.45}.evidence a{color:#506f99}.evidence em{color:#8e7b65;font-style:normal}.resolution-meta{margin-bottom:10px;color:#8692a3;font-size:8px}.modify-form label{display:flex;flex-direction:column;gap:4px;margin-top:7px;font-size:9px}.modify-form input,.modify-form select,.modify-form textarea{padding:7px;color:#37455b;font-size:10px;background:#fff;border:1px solid #dbe2ea;border-radius:5px}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.form-actions,.candidate-actions{display:flex;justify-content:flex-end;gap:7px}.form-actions{margin-top:10px}.form-actions button,.candidate-actions button{padding:6px 9px;font-size:9px;border:1px solid #d5dde8;border-radius:5px}.form-actions .primary,.candidate-actions button:first-child{color:#fff;background:#4d6d99;border-color:#4d6d99}.candidate-actions{padding:10px 15px 12px;border-top:1px solid #e3e7ed}.candidate-actions .modify{color:#49698f;background:#f1f5fa}.candidate-actions .reject{color:#8b5963;background:#fff7f8;border-color:#ead4d8}.candidate-actions button:disabled{cursor:not-allowed;opacity:.5}.readonly-note{padding:10px 15px;color:#8d97a5;font-size:9px;border-top:1px solid #e3e7ed}
</style>
